Import('*')

SimObject('SimpleAccelObj.py', sim_objects=['SimpleAccelObj'])
SimObject('PimAccel.py', sim_objects=['PimAccel','PIMIODriver'])
SimObject('SpadMem.py', sim_objects=['SpadMem'])
SimObject('PimCore.py', sim_objects=['PimCore'])


Source('simple_accelobj.cc')
Source('pim_accel.cc')
Source('pimio_driver.cc')
Source('spad_mem.cc')
Source('pim_core.cc')

DebugFlag('SimpleAccelObj')
DebugFlag('PimAccel')
DebugFlag('SpadMem')
DebugFlag('PimCore')